image: "python:3.8"

before_script:
  - python --version
  - pip install -r requirements.txt
  - python3 manage.py collectstatic

stages:
  - Static Analysis

flake8:
  stage: Static Analysis
  needs: []
  script:
  - flake8 --max-line-length=120 *.py