image: "python:3.8"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Static Analysis
  - Unit Test

flake8:
  stage: Static Analysis
  needs: []
  script:
  - flake8 --max-line-length=120 *.py

unit_test:
  stage: Unit Test
  needs: []
  script:
    - python manage.py test